import images from '../../assets/men/images';

export const menInnerwear = [
  {
    id: 1,
    name: "Cotton Crew Neck Vest",
    price: 399,
    colors: ["White", "Black", "Grey"],
    images: {
      White: [images.vestWhite],
      Black: [images.vestBlack],
      Grey: [images.vestGrey],
    },
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "men-vests",
    description: "Soft cotton vest for all-day comfort and breathability.",
    material: "Cotton 100%",
    care: "Machine wash at 30°C",
    delivery: "Free delivery on orders over Rs. 500. Standard delivery: Rs. 50.",
    tag: ["Premium", "New Arrivals"],
    rating: 5
  },
  {
    id: 2,
    name: "Men's Boxer Briefs (Pack of 3)",
    price: 899,
    colors: ["Black", "Grey", "Navy"],
    images: {
      Black: [images.boxerBlack],
      Grey: [images.boxerGrey],
      Navy: [images.navyBoxer],
    },
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "men-briefs",
    description: "Comfortable boxer briefs with elastic waistband for a perfect fit.",
    material: "Cotton 95%, Elastane 5%",
    care: "Machine wash at 30°C",
    delivery: "Free delivery on orders over Rs. 500. Standard delivery: Rs. 50.",
   tag: ["Best Seller", "New Arrivals"],
   rating: 4
  },
  {
    id: 3,
    name: "Men's Trunks (Pack of 2)",
    price: 699,
    colors: ["Black", "White"],
    images: {
      Black: [images.trunkBlack],
      White: [images.trunkWhite],
    },
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "men-trunks",
    description: "Breathable cotton trunks for everyday wear.",
    material: "Cotton 100%",
    care: "Machine wash at 30°C",
    delivery: "Free delivery on orders over Rs. 500. Standard delivery: Rs. 50.", 
    tag: [ "Best Seller"],
    rating: 5
  },
  {
    id: 4,
    name: "Men's Thermal Innerwear Set",
    price: 1299,
    colors: ["Grey", "Black"],
    images: {
      Grey: [images.thermalGrey],
      Black: [images.thermalBlack],
    },
    sizes: ["M", "L", "XL", "XXL"],
    category: "men-thermal",
    description: "Warm and soft thermal innerwear for winter comfort.",
    material: "Cotton 60%, Polyester 40%",
    care: "Machine wash at 30°C",
    delivery: "Free delivery on orders over Rs. 500. Standard delivery: Rs. 50.",
  rating: 4
  },
  {
    id: 5,
    name: "Men's Sleeveless Innerwear",
    price: 349,
    colors: ["White", "Black"],
    images: {
      White: [images.sleevelessWhite],
      Black: [images.sleevelessBlack],
    },
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "men-sleeveless",
    description: "Lightweight sleeveless innerwear for comfort and ease of movement.",
    material: "Cotton 100%",
    care: "Machine wash at 30°C",
    delivery: "Free delivery on orders over Rs. 500. Standard delivery: Rs. 50.",
   tag: [ "Best Seller"],
   rating: 5,
  },
  {
    id: 6,
    name: "Classic Cotton Vest",
    price: 429,
    colors: ["White", "Black"],
    images: {
      White: [images.vestWhite],
      Black: [images.vestBlack],
    },
    sizes: ["S", "M", "L", "XL"],
    category: "men-vests",
    description: "Classic design with breathable cotton fabric.",
    material: "Cotton 100%",
    care: "Machine wash at 30°C",
    delivery: "Free delivery on orders over Rs. 500. Standard delivery: Rs. 50.",
    rating: 4
  },
  {
    id: 7,
    name: "Comfort Boxer Briefs",
    price: 799,
    colors: ["Black", "Grey"],
    images: {
      Black: [images.boxerBlack],
      Grey: [images.boxerGrey],
    },
    sizes: ["M", "L", "XL", "XXL"],
    category: "men-briefs",
    description: "Comfort and flexibility for all-day wear.",
    material: "Cotton 95%, Elastane 5%",
    care: "Machine wash at 30°C",
    delivery: "Free delivery on orders over Rs. 500. Standard delivery: Rs. 50.",
 tag: ["Premium"],
 rating: 5
  },
  {
    id: 8,
    name: "Performance Trunks",
    price: 749,
    colors: ["Black", "White"],
    images: {
      Black: [images.trunkBlack],
      White: [images.trunkWhite],
    },
    sizes: ["S", "M", "L"],
    category: "men-trunks",
    description: "Moisture-wicking fabric to keep you dry and comfortable.",
    material: "Cotton 90%, Polyester 10%",
    care: "Machine wash cold",
    delivery: "Standard delivery: Rs. 50.",
    rating: 5
  },
  {
    id: 9,
    name: "Thermal Long Sleeve Top",
    price: 999,
    colors: ["Grey", "Black"],
    images: {
      Grey: [images.thermalGrey],
      Black: [images.thermalBlack],
    },
    sizes: ["M", "L", "XL"],
    category: "men-thermal",
    description: "Insulating layer perfect for cold weather.",
    material: "Cotton 50%, Polyester 50%",
    care: "Machine wash at 30°C",
    delivery: "Standard delivery: Rs. 50.",
    rating: 5
  },
  {
    id: 10,
    name: "Basic Sleeveless Tank",
    price: 329,
    colors: ["White"],
    images: {
      White: [images.sleevelessWhite],
    },
    sizes: ["S", "M", "L"],
    category: "men-sleeveless",
    description: "Simple and soft tank for layering or lounging.",
    material: "Cotton 100%",
    care: "Machine wash cold",
    delivery: "Standard delivery: Rs. 50.",
       rating: 4
  },
  {
    id: 11,
    name: "Premium Cotton Vest",
    price: 459,
    colors: ["White", "Black", "Grey"],
    images: {
      White: [images.vestWhite],
      Black: [images.vestBlack],
      Grey: [images.vestGrey],
    },
    sizes: ["M", "L", "XL", "XXL"],
    category: "men-vests",
    description: "High-quality cotton vest with superior breathability.",
    material: "Cotton 100%",
    care: "Machine wash at 30°C",
    delivery: "Free delivery on orders over Rs. 500.",
    tag: ["Premium"],
       rating: 4
  },
  {
    id: 12,
    name: "Classic Briefs",
    price: 599,
    colors: ["Black", "Grey"],
    images: {
      Black: [images.boxerBlack],
      Grey: [images.boxerGrey],
    },
    sizes: ["S", "M", "L", "XL"],
    category: "men-briefs",
    description: "Classic briefs with snug fit for everyday wear.",
    material: "Cotton 95%, Elastane 5%",
    care: "Machine wash at 30°C",
    delivery: "Standard delivery: Rs. 50.",
         tag: ["HotPick"],
            rating: 4
  },
  {
    id: 13,
    name: "Everyday Trunks",
    price: 679,
    colors: ["Black", "White"],
    images: {
      Black: [images.trunkBlack],
      White: [images.trunkWhite],
    },
    sizes: ["S", "M", "L", "XL"],
    category: "men-trunks",
    description: "Daily wear trunks with premium comfort.",
    material: "Cotton 100%",
    care: "Machine wash cold",
    delivery: "Free delivery on orders over Rs. 500.",
         tag: ["HotPick"],
            rating: 4
  },
  {
    id: 14,
    name: "Winter Thermal Bottoms",
    price: 1099,
    colors: ["Grey", "Black"],
    images: {
      Grey: [images.thermalGrey],
      Black: [images.thermalBlack],
    },
    sizes: ["M", "L", "XL"],
    category: "men-thermal",
    description: "Warm thermal bottoms to beat the cold.",
    material: "Cotton 60%, Polyester 40%",
    care: "Machine wash at 30°C",
    delivery: "Free delivery on orders over Rs. 500.",
     tag: ["HotPick"],
        rating: 4
  },
  {
    id: 15,
    name: "Athletic Sleeveless Vest",
    price: 379,
    colors: ["White", "Black"],
    images: {
      White: [images.sleevelessWhite],
      Black: [images.sleevelessBlack],
    },
    sizes: ["S", "M", "L"],
    category: "men-sleeveless",
    description: "Ideal for gym and outdoor activities.",
    material: "Cotton 90%, Elastane 10%",
    care: "Machine wash cold",
    delivery: "Standard delivery: Rs. 50.",
         tag: ["HotPick"],
            rating: 4
  }
];

// Sizes
export const sizes = ["XS", "S", "M", "L", "XL", "XXL"];

// Size guide
export const sizeGuide = {
  "XXS-S": [
    { label: "UK", values: ["28", "30R-32R", "34R-36R"] },
    { label: "EUR", values: ["38", "40-42", "44-46"] },
    { label: "Chest cm", values: ["74-78", "78-86", "86-90"] },
    { label: "Chest inch", values: ["29-30¾", "30¾-33¾", "33¾-35½"] },
    { label: "Waist cm", values: ["62-66", "66-74", "74-78"] },
    { label: "Waist inch", values: ["24½-26", "26-29¼", "29¼-30¾"] },
    { label: "Arm length cm", values: ["59", "59", "59-60"] },
    { label: "Arm length inch", values: ["23¼", "23¼", "23¼-23¾"] },
    { label: "Neckline cm", values: ["33", "34-35", "36"] },
    { label: "Neckline inch", values: ["13", "13¼-13¾", "14"] },
  ],
  "M-XL": [
    { label: "UK", values: ["38-40", "42-44", "46-48"] },
    { label: "EUR", values: ["48-50", "52-54", "56-58"] },
    { label: "Chest cm", values: ["90-96", "97-104", "105-112"] },
    { label: "Chest inch", values: ["35½-37¾", "38-41", "41-44"] },
    { label: "Waist cm", values: ["79-84", "85-92", "93-100"] },
    { label: "Waist inch", values: ["31¼-33", "33½-36", "36½-39"] },
    { label: "Arm length cm", values: ["60-61", "61-62", "62-63"] },
    { label: "Arm length inch", values: ["23¾-24", "24-24½", "24½-25"] },
    { label: "Neckline cm", values: ["37", "38-39", "40"] },
    { label: "Neckline inch", values: ["14½", "15-15¼", "15¾"] },
  ],
  "XXL-3XL": [
    { label: "UK", values: ["50-52", "54-56", "58-60"] },
    { label: "EUR", values: ["60-62", "64-66", "68-70"] },
    { label: "Chest cm", values: ["113-120", "121-128", "129-136"] },
    { label: "Chest inch", values: ["44½-47", "47½-50", "50½-53½"] },
    { label: "Waist cm", values: ["101-108", "109-116", "117-124"] },
    { label: "Waist inch", values: ["39½-42½", "43-45½", "46-49"] },
    { label: "Arm length cm", values: ["63-64", "64-65", "65-66"] },
    { label: "Arm length inch", values: ["25-25½", "25½-26", "26-26½"] },
    { label: "Neckline cm", values: ["41", "42-43", "44"] },
    { label: "Neckline inch", values: ["16", "16½-16¾", "17"] },
  ],
};
